name: build

on:
  push:
    branches:
      - main

jobs:
  go-to-sleep:
    name: get-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sleep a little while
        shell: bash
        run: |
          sleep 300
