name: build

on:
  push:
    branches:
      - main

jobs:
  go-to-sleep:
    name: go-to-sleep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sleep a little while
        shell: bash
        run: |
          while true; do
            sleep 2
            date "+%F@%T"
          done
