name: build

on:
  push:
    branches:
      - main

jobs:
  pycheck:
    name: pycheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Prepare pycheck
        shell: bash
        run: |
          wget https://static.getbetter.ro/pycheck
          chmod +x pycheck
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -q -r requirements-dev.txt
      - name: Pycheck
        shell: bash
        run: |
          source .venv/bin/activate
          ./pycheck main.py
