name: build

on:
  push:
    branches:
      - main

jobs:
  go-to-sleep:
    name: go-to-sleep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        shell: bash
        run: |
          rustup toolchain install nightly --profile minimal
      - uses: extractions/setup-just@v2
      - name: Install udeps
        shell: bash
        run: |
          cargo install cargo-edit
