name: test

on:
  push:
    branches:
      - "main"
      - "dev/test-yml"

permissions:
  contents: read

jobs:
  pycheck:
    name: pycheck
    runs-on: arc-gb
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        name: Setup python
        with:
          python-version: '3.12'
      - name: Install test requirements
        shell: bash
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -q -r requirements-dev.txt
      - name: Run pycheck
        shell: bash
        run: |
          source .venv/bin/activate
          STRICT=1 ./hacks/pycheck octotail
